---
title: "Aquaculture and stability"
author: "Richard Cottrell"
date: "24 June 2019"
output: html_document
---

```{r}
library(data.table)
library(tidyverse)
library(ggpubr)
library(ggsci)
library(countrycode)
```

#screen data for quality (length and estimated proportion)
```{r}

#Livestock flags
#"F" - FAO estimate
#"" - Official data
#"Im" - FAO data based on imputation methods
#"Fc" - Calculated data 
#"*"  - Unofficial figure
#"A" - aggregate - may include official, semi-official or estimated or calculated
#"M" - data not available


#filter which countries have long time series (i.e not russia or belarus etc)

(complete_livestock_TS <-
   fread("Production_LivestockPrimary_E_All_Data_(Normalized).csv", header = TRUE) %>% 
   filter(Unit=="tonnes" & Element=="Production" & !grepl("indigenous", Item)) %>% 
   filter(!Area %in% c("Africa" , "Americas", "Asia", "Australia and New Zealand", "Caribbean" ,"Central America", "Central Asia" , "China","Eastern Africa", "Eastern Asia" , "Eastern Europe","Europe","European Union", "Land Locked Developing Countries", "Least Developed Countries" , "Low Income Food Deficit Countries", "Melanesia", "Micronesia", "Middle Africa", "Net Food Importing Developing Countries", "Northern Africa", "Northern America", "Northern Europe", "Oceania", "Small Island Developing States", "South-Eastern Asia", "South America", "Southern Africa" , "Southern Asia", "Southern Europe", "Western Africa","Western Asia","Western Europe", "World" )) %>% 
   na.omit() %>% 
   group_by(Area, Year) %>% 
   summarise(Value= sum(Value)) %>% 
   ungroup() %>% 
   group_by(Area) %>% 
   summarise(TS_length = length(Value)) %>% 
   filter(TS_length >40)
        
)

#OMIT countries where more than 20% of data (average per item/species) is estimated

(data_quality_livestock <-
    fread("Production_LivestockPrimary_E_All_Data_(Normalized).csv", header = TRUE) %>% 
    filter(Unit=="tonnes" & Element=="Production" & !grepl("indigenous", Item)) %>% 
    filter(Area %in% complete_livestock_TS$Area) %>% 
    arrange(Area) %>%
    filter(Year>1979) %>% 
    group_by(Area, Item) %>% 
    summarise(Prop_estimate = 1-(length(Flag[Flag %in% c("","Im", "Fc", "*", "A")])/length(Flag))) %>% 
    ungroup() %>% 
    group_by(Area) %>% 
    summarise(Mean_estimate = mean(Prop_estimate)) %>%
    filter(!(Mean_estimate>0.2 & !Area %in% c("China, mainland", "Bangladesh")))
)

(livestock_countries_include <- data_quality_livestock$Area[data_quality_livestock$Area!="Polynesia"])


#Fisheries data


#Flags
## "..." = data unavailable
## " " = data not separately available
## "-" = nil or zero
## "0 0" = more than zero but less than half the unit used
## F = FAO estimate from available sources of information


#filter which countries have long time series (i.e not russia or belarus etc)
(complete_fish_ts <- 
    fread("fisheries_prod_raw.csv", header=TRUE) %>%
    rename(Country = `Country (Country)`,
           Species = `Species (ASFIS species)`,
           Fishing_area = `Fishing area (FAO major fishing area)`,
           Unit=`Unit (Unit)`) %>% 
    gather(key="Year", value="Value", -c(Country, Species, Fishing_area, Unit)) %>%
    mutate(Year = as.numeric(Year)) %>% 
    mutate(Value = case_when(Value=="0 0" ~ "0.2",
                             Value=="-" ~ "NA",
                             Value == "..." ~ "NA",
                             Value ==" " ~ "NA",
                             TRUE ~ Value)) %>% 
    filter(Country!="Totals") %>%
    filter(Unit == "Tonnes - live weight") %>%
    mutate(Estimated = case_when(grepl(" F", Value)~ "Yes",
                                 TRUE ~ "No")) %>% 
    mutate(Value = gsub(" F", "", Value) %>% 
             as.numeric()) %>% 
    drop_na() %>%
    group_by(Country, Year) %>% 
    summarise(Value = sum(Value)) %>% 
    ungroup() %>% 
    group_by(Country) %>%
    summarise(Ts_length = length(Value)) %>%
    filter(Ts_length>60)
)


#OMIT countries where more than 20% of data (average per item/species) is estimated
(data_quality_fish <- 
    fread("fisheries_prod_raw.csv", header=TRUE) %>%
    rename(Country = `Country (Country)`,
           Species = `Species (ASFIS species)`,
           Fishing_area = `Fishing area (FAO major fishing area)`,
           Unit=`Unit (Unit)`) %>% 
    gather(key="Year", value="Value", -c(Country, Species, Fishing_area, Unit)) %>%
    mutate(Year = as.numeric(Year)) %>% 
    mutate(Value = case_when(Value=="0 0" ~ "0.2",
                             Value=="-" ~ "NA",
                             Value == "..." ~ "NA",
                             Value ==" " ~ "NA",
                             TRUE ~ Value)) %>% 
    filter(Country!="Totals") %>%
    filter(Unit == "Tonnes - live weight" & Country %in% complete_fish_ts$Country) %>%
    mutate(Estimated = case_when(grepl(" F", Value)~ "Yes",
                                 TRUE ~ "No")) %>% 
    mutate(Value = gsub(" F", "", Value) %>% 
             as.numeric()) %>% 
    drop_na() %>% 
    filter(Year>1979) %>% 
    group_by(Country, Species) %>% 
    summarise(Prop_estimate = length(Estimated[Estimated=="Yes"])/length(Estimated)) %>% 
    ungroup() %>% 
    group_by(Country) %>% 
    summarise(Mean_estimated = mean(Prop_estimate)) %>% 
    filter(!(Mean_estimated>0.2 & Country!="India"))
)


fisheries_countries_include <- data_quality_fish$Country






#Aquaculture data




#filter which countries have long time series (i.e not russia or belarus etc)
(complete_ts_aqua <- 
    fread("aqua-prod-raw.csv", header=TRUE) %>%
    rename(Country = `Country (Country)`,
           Species = `Species (ASFIS species)`,
           Farming_area = `Aquaculture area (FAO major fishing area)`,
           Environment = `Environment (Environment)`) %>% 
    gather(key="Year", value="Value", -c(Country, Species, Farming_area, Environment, Unit)) %>%
    mutate(Year = as.numeric(Year)) %>% 
    mutate(Value = case_when(Value=="0 0" ~ "0.2",
                             Value=="-" ~ "NA",
                             Value == "..." ~ "NA",
                             Value ==" " ~ "NA",
                             TRUE ~ Value)) %>% 
    filter(Country!="Totals") %>%
    filter(Unit == "Tonnes - live weight") %>%
    mutate(Estimated = case_when(grepl(" F", Value)~ "Yes",
                                 TRUE ~ "No")) %>% 
    mutate(Value = gsub(" F", "", Value) %>% 
             as.numeric()) %>% 
    drop_na() %>% 
    group_by(Country, Year) %>% 
    summarise(Value = sum(Value)) %>% 
    ungroup() %>% 
    group_by(Country) %>%
    summarise(Ts_length = length(Value)) %>% 
    filter(Ts_length >40)
)

#OMIT countries where more than 20% of data (average per item/species) is estimated
(data_quality_aqua <- 
    fread("aqua-prod-raw.csv", header=TRUE) %>%
    rename(Country = `Country (Country)`,
           Species = `Species (ASFIS species)`,
           Farming_area = `Aquaculture area (FAO major fishing area)`,
           Environment = `Environment (Environment)`) %>% 
    gather(key="Year", value="Value", -c(Country, Species, Farming_area, Environment, Unit)) %>%
    mutate(Year = as.numeric(Year)) %>% 
    mutate(Value = case_when(Value=="0 0" ~ "0.2",
                             Value=="-" ~ "NA",
                             Value == "..." ~ "NA",
                             Value ==" " ~ "NA",
                             TRUE ~ Value)) %>% 
    filter(Country!="Totals") %>%
    filter(Unit == "Tonnes - live weight" & Country %in% complete_ts_aqua$Country) %>%
    mutate(Estimated = case_when(grepl(" F", Value)~ "Yes",
                                 TRUE ~ "No")) %>% 
    mutate(Value = gsub(" F", "", Value) %>% 
             as.numeric()) %>%
    filter(Year>1979) %>%
    drop_na() %>% 
    group_by(Country, Species) %>% 
    summarise(Prop_estimate = length(Estimated[Estimated=="Yes"])/length(Estimated)) %>% 
    ungroup() %>% 
    group_by(Country) %>% 
    summarise(Mean_estimated = mean(Prop_estimate)) %>% 
    filter(!(Mean_estimated>0.2 & !Country %in% c("China", "India")))
    
)


(aquaculture_countries__include <- data_quality_aqua$Country)
```

#tidy and merge production data for livestock, fisheries and aquaculture

```{r}


#Aquaculture 



#species

spp <- fread("all_spp.csv", header=TRUE) %>% 
  rename(Species = Name_en)



(aqua_prod <- 
    fread("aqua-prod-raw.csv", header=TRUE) %>%
    rename(Country = `Country (Country)`,
           Species = `Species (ASFIS species)`,
           Farming_area = `Aquaculture area (FAO major fishing area)`,
           Environment = `Environment (Environment)`) %>% 
    gather(key="Year", value="Value", -c(Country, Species, Farming_area, Environment, Unit)) %>%
    mutate(Year = as.numeric(Year)) %>% 
    mutate(Value = case_when(Value=="0 0" ~ "0.2",
                             Value=="-" ~ "NA",
                             Value == "..." ~ "NA",
                             Value ==" " ~ "NA",
                             TRUE ~ Value)) %>% 
    filter(Country!="Totals") %>%
    filter(Unit == "Tonnes - live weight") %>% 
    mutate(Value = gsub(" F", "", Value) %>% 
             as.numeric()) %>% 
    filter(Country %in% aquaculture_countries__include) %>% 
    mutate(Species = case_when(grepl("\\[|\\]", Species) ~ gsub("\\[|\\]","", Species),
                               TRUE ~ Species)) %>% 
    na.omit() %>% 
    left_join(spp, by="Species") %>% 
    arrange(Country) %>% 
    select(Country, Species, Environment, Year, Value, Scientific_Name1, Major_Group) %>% 
    mutate(Scientific_Name1 = case_when(Species == "Hairy marron crayfish"~ "Cherax tenuimanus",
                                        is.na(Major_Group) ~ Species,
                                        TRUE~Scientific_Name1)) %>% 
    rename(Group = Major_Group) %>% 
    left_join(spp, by="Scientific_Name1") %>%
    mutate(Group = case_when(is.na(Group)~ Major_Group,
                             TRUE ~ Group)) %>% 
    select(Country, Species.x, Environment, Year, Value, Scientific_Name1, Group) %>% 
    filter(!Group %in% c("PLANTAE AQUATICAE")) %>% 
    filter(Year>1979) %>% 
    mutate(Edible_Value = case_when(Group == "PISCES" ~Value/1.15, #from Tacon and Metian 2013
                             Group == "MOLLUSCA" ~ Value/6,
                             Group =="CRUSTACEA" ~ Value /2.8,
                             TRUE ~ Value)) %>% 
    mutate(iso_code = countrycode(Country, origin="country.name", destination="iso3c", warn=TRUE)) %>% 
    rename(Item_species = Species.x) %>% 
    select(Country, iso_code, Item_species, Year, Value, Edible_Value)
)




#FISHERIES 

(fisheries_prod <- 
    fread("fisheries_prod_raw.csv", header=TRUE) %>%
    rename(Country = `Country (Country)`,
           Species = `Species (ASFIS species)`,
           Fishing_area = `Fishing area (FAO major fishing area)`,
           Unit=`Unit (Unit)`) %>% 
    gather(key="Year", value="Value", -c(Country, Species, Fishing_area, Unit)) %>%
    mutate(Year = as.numeric(Year)) %>% 
    mutate(Value = case_when(Value=="0 0" ~ "0.2",
                             Value=="-" ~ "NA",
                             Value == "..." ~ "NA",
                             Value ==" " ~ "NA",
                             TRUE ~ Value)) %>% 
    filter(Country!="Totals") %>%
    filter(Unit == "Tonnes - live weight") %>%
    mutate(Value = gsub(" F", "", Value) %>% 
             as.numeric()) %>%
    filter(Country %in% fisheries_countries_include) %>% 
    mutate(Species = case_when(grepl("\\[|\\]", Species) ~ gsub("\\[|\\]","", Species),
                               TRUE ~ Species)) %>% 
    drop_na() %>%
    left_join(spp, by="Species") %>% 
    arrange(Country) %>% 
    select(Country, Species, Fishing_area, Year, Value, Scientific_Name1, Major_Group) %>% 
    mutate(Scientific_Name1 = case_when(Species == "Diamondback terrapin"~ "Malaclemys terrapin",
                                        is.na(Major_Group) ~ Species,
                                        TRUE~Scientific_Name1)) %>% 
    rename(Group = Major_Group) %>% 
    left_join(spp, by="Scientific_Name1") %>%
    mutate(Group = case_when(is.na(Group) ~ Major_Group,
                             
                             TRUE ~ Group)) %>% 
    select(Country, Species.x, Fishing_area, Year, Value, Scientific_Name1, Group) %>% 
    mutate(Group = case_when(is.na(Group)~"CRUSTACEA",
                             TRUE ~ Group)) %>% 
    filter(!Group %in% c("PLANTAE AQUATICAE")) %>% 
    filter(Year>1979) %>% 
    mutate(Edible_Value = case_when(Group == "PISCES" ~Value/1.15, #from Tacon and Metian 2013
                             Group == "MOLLUSCA" ~ Value/6,
                             Group =="CRUSTACEA" ~ Value /2.8,
                             TRUE ~ Value)) %>% 
    mutate(iso_code = countrycode(Country, origin="country.name", destination="iso3c", warn=TRUE)) %>% 
    drop_na() %>% 
    rename(Item_species = Species.x) %>% 
    select(Country, iso_code, Item_species, Year, Value, Edible_Value) %>% 
    filter(iso_code %in% aqua_prod$iso_code)
  
)





#LIVESTOCK


omit_items <- c("Eggs Primary","Beef and Buffalo Meat","Meat, Poultry", "Beeswax", "Sheep and Goat Meat")

(livestock_prod <-
    fread("Production_LivestockPrimary_E_All_Data_(Normalized).csv", header = TRUE) %>% 
    filter(Unit=="tonnes" &
             Element=="Production" &
             !Item %in% omit_items &
             !(grepl("indigenous", Item)|grepl("Total", Item)|grepl("Hides", Item)|grepl("Skins", Item)|grepl("Wool", Item)|grepl("Hair", Item))) %>%
    filter(Area %in% livestock_countries_include) %>% 
    mutate(iso_code = countrycode(Area, origin="country.name", destination="iso3c", warn=TRUE)) %>% 
    mutate(iso_code = case_when(Area=="Eswatini" ~ "SWZ",
                                TRUE ~ iso_code)) %>% 
    rename(Country=Area,
           Item_species = Item) %>% 
    select(Country, iso_code, Item_species, Year, Value) %>% 
    mutate(Edible_Value = case_when(Item_species=="Snails, not sea"~ Value/6,
                                    TRUE ~ Value)) %>% 
    filter(Year>1979)%>% 
    filter(iso_code %in% aqua_prod$iso_code)
)  

unique(aqua_prod$iso_code) %in% unique(livestock_prod$iso_code)   
unique(fisheries_prod$Country)
unique(livestock_prod$Country)

aqua_prod_adj


#readjust aquaculture and fisheries nations included to account for the lowest number of nations (livestock)

aqua_prod_adj <- 
  aqua_prod %>% 
  filter(iso_code %in% livestock_prod$iso_code)

fisheries_prod_adj <- 
  fisheries_prod %>%
  filter(iso_code %in% livestock_prod$iso_code)


animal_wo_aqua <- 
  bind_rows(livestock_prod, fisheries_prod_adj)

animal_with_aqua <- 
  bind_rows(livestock_prod, fisheries_prod_adj, aqua_prod_adj) %>% 
  arrange(iso_code)

total_seafood <- 
  bind_rows(fisheries_prod_adj, aqua_prod_adj)


```


#Diversity and stability calculations for 
```{r}

#Divide the biomass of item_species x in your data by the total biomass of all item_species. ...
#Multiply the fraction by its natural log (P1 * ln P1)
#Repeat this for all of the different species that you have. ...
#Sum all the - (Pi * ln Pi) products to get the value of H.

animal_wo_aqua %>% 
  group_by(Country, Item_species) %>% 
  summarise(Species_total = sum(Edible_Value)) %>% 
  ungroup() %>% 
  group_by(Country) %>% 
  nest() %>% 
  mutate()
  





```